apiVersion: apps/v1
kind: Deployment
metadata: 
  name: springboot-k8s-deployment
spec: 
  selector: 
    matchLabbels:
      app: springboot-k8s
  replicas: 2
  templates: 
   metadata:
     labels:
       app: springboot-k8s
  spec:
    containers:
      -name: springboot-k8s
     
      image: manoj21333/employees 
      imagePullPolicy: IfNotPresent
      ports:
       -containerPort: 8080

---



apiVersion: v1
kind: Service
metadata: 
   name: springboot-k8ssvc
spec: 
  selector:
   app: springboot-k8s
  ports:
     -protocol: "TCP"
     targetPort: 8080
type: NodePort